name: Build and Decompile APK

on:
  workflow_dispatch:
    inputs:
      apk_url:
        description: 'URL of the APK file to download'
        required: true
        default: 'https://github.com/John4650-hub/whisper_android/raw/master/release/WhisperASR.apk'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'  # Specify the Java version you need
          distribution: 'temurin'
      - name: Run Bash Script
        run: |
          chmod +x ./install_apktool.sh
          ./install_apktool.sh "${{ github.event.inputs.apk_url }}"

      - name: Upload Recompiled APK
        uses: actions/upload-artifact@v2
        with:
          name: recompiled-apk
          path: recompiled.apk
        env:
          GITHUB_TOKEN: ${{ secrets.TK }}
