name: Build and Decompile APK

on:
  push:
    branches: 
      - master
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'  # Specify the Java version you need
          distribution: 'temurin'
      - name: Run Bash Script
        run: |
          chmod +x ./install_apktool.sh
          ./install_apktool.sh "https://raw.githubusercontent.com/John4650-hub/whisper_android/master/release/WhisperASR.apk"

      - name: Upload Recompiled APK
        uses: actions/upload-artifact@v4
        with:
          name: recompiled-apk
          path: recompiled.apk
        env:
          GITHUB_TOKEN: ${{ secrets.TK }}
